### ISSUE TITLE
Can you generate all advanced services?

### ISSUE THREAD

**Issue by grant** [mtgto/dts-google-apps-script-advanced#1]
Hey @mtgto,
This tool/approach looks cool and could be better than hand-writing types.

I think you used this tool for this PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34073

Can you describe the technique more?
- How To Download

Do you mean the json from downloads like this?
https://script.google.com/macros/autocomplete/dep/apiary/mirror/v1

Maybe we can generate all types.

**Comment by mtgto** [comment]
@grant 

> I think you used this tool for this PR:

Yes. I develop this tool to use Calendar / AdminDirectory in GAS.

> Can you describe the technique more?
> Do you mean the json from downloads like this?
> https://script.google.com/macros/autocomplete/dep/apiary/mirror/v1

Yes.
Before develop this tool, I try to use type definition in google-api-nodejs-client: https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/calendar/v3.ts

but it doesn't match structures in GAS.
This is why i create this automated generator.

> Maybe we can generate all types.

Maybe we can.
I'm newbie GAS, and use advanced Calendar and Admin Directory API only.
It is the reason why I create the PR for above two services type definitions.

**Comment by mtgto** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34212

**Comment by mtgto** [comment]
I know this issue is not fixed because there still exists some schema class has no definition in autocomplete jsons.

ex:

- ReclaimStudentSubmissionRequest in classroom_v1
- EmbeddedDrawingProperties in docs_v1

and so on.
