### ISSUE TITLE
Invalid variable name "start-date"

### ISSUE THREAD

**Issue by grant** [mtgto/dts-google-apps-script-advanced#2]
The generator sometimes creates invalid variables:

For example, `start-date` is an invalid variable
"analytics_v3.d.ts"

**Comment by mtgto** [comment]
OMG, `start-date` is broken name.

It is easy to fix to rename `startDate`, but I think it is autocomplete definition json's problem.
Can you fix autocomplete definition?

**Comment by grant** [comment]
I'm going to just manually fix this for myself.

**Comment by mtgto** [comment]
May I close this issue?

**Comment by grant** [comment]
Well, is it fixed?

**Comment by mtgto** [comment]
It's your issue.

**Comment by grant** [comment]
Well, it hasn't been fixed. The code in this repo hasn't been modified since I created the issue.

**Comment by mtgto** [comment]
@grant I asked you to fix autocomplete definition, but you answer `I'm going to just manually fix this for myself.`.

And YOU ALREADY FIXED this issue in DefinitelyTyped pull request.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34212
https://github.com/grant/DefinitelyTyped/blob/fbe6e45ab2e23b027ca98ae374d94c29eb09446a/types/google-apps-script/apis/analytics_v3.d.ts#L13

What I have to do?

**Comment by grant** [comment]
I cannot modify this repo, but I can fix the DT types for that DT repo.

It would be nice if this repo handled this issue so I didn't need to manually fix it for when I publish to DT.

**Comment by mtgto** [comment]
Fix it, maybe.
https://github.com/mtgto/dts-google-apps-script-advanced/commit/3777b7e7800fe38cabe65c7cb5f819990d75a9f0

**Comment by grant** [comment]
Thanks.
