### ISSUE TITLE
"Schema.Empty" should be "void"

### ISSUE THREAD

**Issue by grant** [mtgto/dts-google-apps-script-advanced#3]
Sometimes the generator produces: `Schema.Empty`
I think this should be: `void`

i.e. `peopleapi_v1`

**Comment by mtgto** [comment]
May I close this issue?

**Comment by grant** [comment]
Why would you close it? Has it been fixed?

**Comment by mtgto** [comment]
Because you already fixed it in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34212
https://github.com/grant/DefinitelyTyped/blob/fbe6e45ab2e23b027ca98ae374d94c29eb09446a/types/google-apps-script/apis/peopleapi_v1.d.ts

**Comment by grant** [comment]
Well, I would like to use this repo again when the types have to be updated later.

**Comment by mtgto** [comment]
Fix it in https://github.com/mtgto/dts-google-apps-script-advanced/commit/66a956f9708a54ad0e2e4c88cdc2544b0624e5be
