### ISSUE TITLE
Too many nested namespaces

### ISSUE THREAD

**Issue by grant** [mtgto/dts-google-apps-script-advanced#4]
The TS definitions should be flatter than they are generated. They should generate this:

```ts
declare namespace GoogleAppsScript {
  namespace Analytics_v3 {
    namespace Collection {
      namespace Data {
```

**Comment by mtgto** [comment]
May I close this issue?

**Comment by grant** [comment]
Yes

**Comment by mtgto** [comment]
Fix it in https://github.com/mtgto/dts-google-apps-script-advanced/commit/e48ba353907eebfe5426a57fc9f2ae203e305b4e
