### ISSUE TITLE
Please clarify or update instructions to download the `.json`

### ISSUE THREAD

**Issue by PopGoesTheWza** [mtgto/dts-google-apps-script-advanced#5]
Under the section "How To Download gas-advanced-service-definition-for-autocomplete.json"

1. Open editor of Google Apps Script.
1. Enable Advanced Service in menu.
1. Browser download it.

Maybe the interface has changed but I cannot complete step 3.

Within the Google Apps Script editor, I open the `Resources` menu and select `Advanced Google services...` option. Next the `Advanced Google Services` modal window appears and I can't decide what I should do next.

TIA.

**Comment by mtgto** [comment]
First, toggle ON you interest service, choose OK.

![image](https://user-images.githubusercontent.com/1213991/67568717-ed832d80-f767-11e9-8182-be9bd44ca607.png)

Browser automatically download json.

![image](https://user-images.githubusercontent.com/1213991/67568800-27543400-f768-11e9-8640-6bfb274a9b0e.png)

**Comment by mtgto** [comment]
If you want data, see https://github.com/grant/google-apps-script-dts/tree/master/data_3

**Comment by PopGoesTheWza** [comment]
@mtgto Thanks. As I was working on my fork of [`dts-google-apps-script`](https://github.com/PopGoesTheWza/dts-google-apps-script) and try to update and improve the generated `.d.ts` I wanted to check how the api part was generated.

**Comment by mtgto** [comment]
@PopGoesTheWza `@types/google-apps-script` is now very different from this project create.
This is because @grant rewrite definition files, but this repository does not follow the changes.
I'm sorry if it trouble you...
